export default students=[
	{
		"id": 1,
		"created_at": "2024-06-05 12:02:30",
		"updated_at": "2024-06-05 12:02:30",
		"name": "Jonj",
		"admission_no": "11111",
		"nemis_number": null,
		"assessment_number": null,
		"parentname": null,
		"parent_mobile": null,
		"secondary_mobile": null,
		"dob": null,
		"city": null,
		"town": null,
		"streetaddress": null,
		"mobile": null,
		"email": null,
		"remarks": null,
		"createdby": null,
		"is_active": "1",
		"ipaddress": "127.0.0.1",
		"lasteditedby": 1,
		"teachers_student": "0",
		"deactivated": "1",
		"deactivate_reason": "srequired",
		"fathers_name": null,
		"fathers_phone": null,
		"mothers_name": null,
		"mothers_phone": null,
		"guardians_name": null,
		"guardians_phone": null,
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "form 2",
		"current_class_id": "form 2",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Male",
		"branch_id": "School"
	},
	{
		"id": 2,
		"created_at": "2024-06-05 12:02:30",
		"updated_at": "2024-06-05 12:02:30",
		"name": "Christian Kirlin",
		"admission_no": "ahettttttttttttttttttttt",
		"nemis_number": "swwwwaggggggggf",
		"assessment_number": "sdffggg",
		"parentname": null,
		"parent_mobile": "56669669",
		"secondary_mobile": "686686868",
		"dob": "2024-06-22",
		"city": "Nairobi",
		"town": "Nairobi",
		"streetaddress": "01034",
		"mobile": "0111204383",
		"email": "davidmurichuz2@gmail.com",
		"remarks": null,
		"createdby": null,
		"is_active": "0",
		"ipaddress": "127.0.0.1",
		"lasteditedby": null,
		"teachers_student": "0",
		"deactivated": "0",
		"deactivate_reason": "NA",
		"fathers_name": "gfhfhfhfhffh",
		"fathers_phone": "0111203",
		"mothers_name": "ajjtyyyyyyyyyyyy",
		"mothers_phone": "6866868",
		"guardians_name": "dhdhdfhffhfh",
		"guardians_phone": "58558585",
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "Form 3",
		"current_class_id": "Form 3",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Female",
		"branch_id": "School"
	},
	{
		"id": 3,
		"created_at": "2024-06-05 12:02:30",
		"updated_at": "2024-06-05 12:02:30",
		"name": "Kamau",
		"admission_no": "fsdfsdfd",
		"nemis_number": "G798788",
		"assessment_number": "dfsdf",
		"parentname": null,
		"parent_mobile": "8745252454",
		"secondary_mobile": "984565464",
		"dob": "2024-05-29",
		"city": "Nairobi",
		"town": "thika",
		"streetaddress": "nairobi",
		"mobile": "0112795876",
		"email": "joyseelyn@gmail.com",
		"remarks": null,
		"createdby": null,
		"is_active": "0",
		"ipaddress": "127.0.0.1",
		"lasteditedby": null,
		"teachers_student": "0",
		"deactivated": "0",
		"deactivate_reason": "aasdasda",
		"fathers_name": "luke",
		"fathers_phone": "008004545",
		"mothers_name": "dama",
		"mothers_phone": "6454464",
		"guardians_name": "added",
		"guardians_phone": "87988",
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "Form 3",
		"current_class_id": "Form 4",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Male",
		"branch_id": "School"
	},
	{
		"id": 4,
		"created_at": "2024-06-05 12:24:03",
		"updated_at": "2024-06-05 12:24:03",
		"name": "Jane",
		"admission_no": "fdfhdfdhfhff88",
		"nemis_number": "swwwwaggggggggf",
		"assessment_number": "sdffggg8888",
		"parentname": null,
		"parent_mobile": "4464646",
		"secondary_mobile": "55656556",
		"dob": "2024-06-18",
		"city": "Nairobi",
		"town": "Nairobi",
		"streetaddress": "01034",
		"mobile": "6767667677",
		"email": "e@ma.il",
		"remarks": null,
		"createdby": null,
		"is_active": "0",
		"ipaddress": "127.0.0.1",
		"lasteditedby": null,
		"teachers_student": "0",
		"deactivated": "1",
		"deactivate_reason": "8888",
		"fathers_name": "gfhfhfhfhffh",
		"fathers_phone": "09888888",
		"mothers_name": "ajjtyyyyyyyyyyyy",
		"mothers_phone": "888888888",
		"guardians_name": "dhdhdfhffhfh",
		"guardians_phone": "88888888",
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "Form 3",
		"current_class_id": "Form 3",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Female",
		"branch_id": "School"
	},
	{
		"id": 5,
		"created_at": "2024-06-06 11:57:00",
		"updated_at": "2024-06-06 11:57:00",
		"name": "daskjhkajd",
		"admission_no": "Gt222",
		"nemis_number": "G798788",
		"assessment_number": "213eee",
		"parentname": null,
		"parent_mobile": "8745252454",
		"secondary_mobile": "984565464",
		"dob": "2024-06-06",
		"city": "Nairobi",
		"town": "nairobi",
		"streetaddress": "thika",
		"mobile": "0112795876",
		"email": "admin@gmail.com",
		"remarks": null,
		"createdby": null,
		"is_active": "0",
		"ipaddress": "127.0.0.1",
		"lasteditedby": null,
		"teachers_student": "0",
		"deactivated": "0",
		"deactivate_reason": "hbhbhb",
		"fathers_name": "fsdfd",
		"fathers_phone": "008004545",
		"mothers_name": "dsf",
		"mothers_phone": "6454464",
		"guardians_name": "added",
		"guardians_phone": "87988",
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "Form 4",
		"current_class_id": "Form 4",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Hassan",
		"branch_id": "School"
	},
	{
		"id": 6,
		"created_at": "2024-06-06 11:59:35",
		"updated_at": "2024-06-06 11:59:35",
		"name": "john",
		"admission_no": "55tee",
		"nemis_number": "GTww2",
		"assessment_number": "dfsdf",
		"parentname": null,
		"parent_mobile": "8745252454",
		"secondary_mobile": "984565464",
		"dob": "2024-06-06",
		"city": "Nairobi",
		"town": "nairobi",
		"streetaddress": "thika",
		"mobile": "0112795876",
		"email": "hakim2@gmail.com",
		"remarks": null,
		"createdby": null,
		"is_active": "0",
		"ipaddress": "127.0.0.1",
		"lasteditedby": null,
		"teachers_student": "0",
		"deactivated": "0",
		"deactivate_reason": "hbhbhb",
		"fathers_name": "fsdfd",
		"fathers_phone": "008004545",
		"mothers_name": "dama",
		"mothers_phone": "6454464",
		"guardians_name": "added",
		"guardians_phone": "87988",
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "Form 4",
		"current_class_id": "Form 3",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Hassan",
		"branch_id": "Administration"
	},
	{
		"id": 7,
		"created_at": "2024-06-06 12:16:41",
		"updated_at": "2024-06-06 12:16:41",
		"name": "Joel",
		"admission_no": "12345",
		"nemis_number": "12345",
		"assessment_number": "12q21",
		"parentname": null,
		"parent_mobile": "6556565656",
		"secondary_mobile": "0798222582",
		"dob": "2024-06-04",
		"city": "Nairobi",
		"town": "nairobi",
		"streetaddress": "thika",
		"mobile": "0112795876",
		"email": "paulwebo38@gmail.com",
		"remarks": null,
		"createdby": null,
		"is_active": "0",
		"ipaddress": "127.0.0.1",
		"lasteditedby": null,
		"teachers_student": "0",
		"deactivated": "0",
		"deactivate_reason": ".llllllll",
		"fathers_name": "Joseph",
		"fathers_phone": "008004545",
		"mothers_name": "martha",
		"mothers_phone": "6454464",
		"guardians_name": "Kamau",
		"guardians_phone": "879885555",
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "Form 3",
		"current_class_id": "Form 4",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Male",
		"branch_id": "School"
	},
	{
		"id": 8,
		"created_at": "2024-06-06 12:20:20",
		"updated_at": "2024-06-06 12:20:20",
		"name": "Jonna",
		"admission_no": "jhjh",
		"nemis_number": "GTww2",
		"assessment_number": "12q21",
		"parentname": null,
		"parent_mobile": "6556565656",
		"secondary_mobile": "984565464",
		"dob": "2024-06-04",
		"city": "Nairobi",
		"town": "thika",
		"streetaddress": "thika",
		"mobile": "0112795876",
		"email": "hakim2@gmail.com",
		"remarks": null,
		"createdby": null,
		"is_active": "0",
		"ipaddress": "127.0.0.1",
		"lasteditedby": 1,
		"teachers_student": "0",
		"deactivated": "0",
		"deactivate_reason": "fghf",
		"fathers_name": "Joseph",
		"fathers_phone": "008004545",
		"mothers_name": "martha",
		"mothers_phone": "6454464",
		"guardians_name": "added",
		"guardians_phone": "87988",
		"last_school_attended": null,
		"birth_cert_no": null,
		"upi_no": null,
		"academicyearid": "Year 1",
		"prev_class_id": "Form 4",
		"current_class_id": "Form 3",
		"current_term_id": "Term 1",
		"transfer_term_id": "Term 1",
		"genderid": "Male",
		"branch_id": "School"
    }
]